platform :ios, '8.0'
use_frameworks!


target 'newGQapp' do
   
    pod 'MJRefresh', '~> 3.1.0'
    pod 'MBProgressHUD','~> 0.9.2'
    pod 'AFNetworking', '~> 2.5.0'
    pod 'DeviceUtil', '~> 1.3.2'
    pod 'SVProgressHUD', '~> 2.1.2'
    pod 'DCPathButton', '~> 2.1.3'
    pod 'Mantle', '1.5.5'
    pod 'SDWebImage', '~> 3.8.0'
    pod 'HYBLoopScrollView', '~> 3.0.0'
    pod 'UMengAnalytics', '~> 4.2.4'

    # 腾讯 Bugly
    pod 'Bugly', '~> 2.4.6'
    
    pod 'YYModel', '~> 1.0.4'
    pod 'TYPagerController'

    pod 'Masonry', '~> 1.0.1'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'RongCloudIMKit', '2.7.3'
    #    pod 'HYBMasonryAutoCellHeight', '~> 2.0.1'
    
    # FPS
#    pod 'JPFPSStatus', '~> 0.1'
#  pod 'GDPerformanceView', '~> 1.3.1'
    pod 'SocketRocket'

end




#post_install
#do |installer|
#    installer.pods_project.targets.each
#    do |target|
#        target.build_configurations.each
#        do |config|
#            config.build_settings['ENABLE_BITCODE'] = 'NO'
#        end
#    end
#end
