#import <Foundation/Foundation.h>
@interface ZBValueZBAppDelegatec: NSObject
+ (BOOL)tResumepuchasezbvalue:(NSInteger)ZBValue;
+ (BOOL)RConfigpagestatisticszbvalue:(NSInteger)ZBValue;
+ (BOOL)nApplicationdidfinishlaunchingwithoptionszbvalue:(NSInteger)ZBValue;
+ (BOOL)hLoadconfigzbvalue:(NSInteger)ZBValue;
+ (BOOL)QSetupmessagesoundzbvalue:(NSInteger)ZBValue;
+ (BOOL)pSvpreferrenceconfzbvalue:(NSInteger)ZBValue;
+ (BOOL)jGetscreenshotzbvalue:(NSInteger)ZBValue;
+ (BOOL)uUserdidscreenshortzbvalue:(NSInteger)ZBValue;
+ (BOOL)AInitrootviewcotrollerzbvalue:(NSInteger)ZBValue;
+ (BOOL)wInitlocalnotificationzbvalue:(NSInteger)ZBValue;
+ (BOOL)kIsfirstlaunchedzbvalue:(NSInteger)ZBValue;
+ (BOOL)EUpdatalocalsavedatazbvalue:(NSInteger)ZBValue;
+ (BOOL)HGeturlserpathzbvalue:(NSInteger)ZBValue;
+ (BOOL)JSetupupushwithwithoptionszbvalue:(NSInteger)ZBValue;
+ (BOOL)PSetupumzbvalue:(NSInteger)ZBValue;
+ (BOOL)wApplicationdidreceiveremotenotificationfetchcompletionhandlerzbvalue:(NSInteger)ZBValue;
+ (BOOL)lUsernotificationcenterwillpresentnotificationwithcompletionhandlerzbvalue:(NSInteger)ZBValue;
+ (BOOL)LUsernotificationcenterdidreceivenotificationresponsewithcompletionhandlerzbvalue:(NSInteger)ZBValue;
+ (BOOL)pApplicationdidreceiveremotenotificationzbvalue:(NSInteger)ZBValue;
+ (BOOL)mApplicationdidregisterforremotenotificationswithdevicetokenzbvalue:(NSInteger)ZBValue;
+ (BOOL)jSetupbuglyzbvalue:(NSInteger)ZBValue;
+ (BOOL)jSetupfpszbvalue:(NSInteger)ZBValue;
+ (BOOL)sSetumsharezbvalue:(NSInteger)ZBValue;
+ (BOOL)kApplicationhandleopenurlzbvalue:(NSInteger)ZBValue;
+ (BOOL)aApplicationopenurlsourceapplicationannotationzbvalue:(NSInteger)ZBValue;
+ (BOOL)kApplicationopenurloptionszbvalue:(NSInteger)ZBValue;
+ (BOOL)KApplicationwillresignactivezbvalue:(NSInteger)ZBValue;
+ (BOOL)rApplicationdidenterbackgroundzbvalue:(NSInteger)ZBValue;
+ (BOOL)UApplicationwillenterforegroundzbvalue:(NSInteger)ZBValue;
+ (BOOL)DApplicationdidbecomeactivezbvalue:(NSInteger)ZBValue;
+ (BOOL)IApplicationwillterminatezbvalue:(NSInteger)ZBValue;
+ (BOOL)tGetserverurlzbvalue:(NSInteger)ZBValue;
+ (BOOL)qLoadlaunchimageviewzbvalue:(NSInteger)ZBValue;
+ (BOOL)pLoadfirstdatazbvalue:(NSInteger)ZBValue;
+ (BOOL)KLoadrefreshtokenzbvalue:(NSInteger)ZBValue;

@end
