#import <Foundation/Foundation.h>
@interface ZBValueZBSaiTableViewCellU: NSObject
+ (BOOL)pawakeFromNib:(NSInteger)ZBValue;
+ (BOOL)VSetselectedYAnimated:(NSInteger)ZBValue;
+ (BOOL)JSetscoremodel:(NSInteger)ZBValue;
+ (BOOL)bbasicView:(NSInteger)ZBValue;
+ (BOOL)Xviewline:(NSInteger)ZBValue;
+ (BOOL)eimageBg:(NSInteger)ZBValue;
+ (BOOL)KimageJiaoqiu:(NSInteger)ZBValue;
+ (BOOL)IlabQB:(NSInteger)ZBValue;
+ (BOOL)ElabQBNum:(NSInteger)ZBValue;
+ (BOOL)HviewLineR:(NSInteger)ZBValue;
+ (BOOL)wlabTJ:(NSInteger)ZBValue;
+ (BOOL)HlabTJNum:(NSInteger)ZBValue;
+ (BOOL)CsortLab:(NSInteger)ZBValue;
+ (BOOL)xtimeLab:(NSInteger)ZBValue;
+ (BOOL)seventLab:(NSInteger)ZBValue;
+ (BOOL)vimageAnimation:(NSInteger)ZBValue;
+ (BOOL)UVSlab:(NSInteger)ZBValue;
+ (BOOL)AteamHomeLab:(NSInteger)ZBValue;
+ (BOOL)rteamAwayLab:(NSInteger)ZBValue;
+ (BOOL)HpankouLab:(NSInteger)ZBValue;
+ (BOOL)xpeiLvHomeLab:(NSInteger)ZBValue;
+ (BOOL)kpeilvAwayLab:(NSInteger)ZBValue;
+ (BOOL)hpankouLableft:(NSInteger)ZBValue;
+ (BOOL)ipeiLvHomeLableft:(NSInteger)ZBValue;
+ (BOOL)CpeilvAwayLableft:(NSInteger)ZBValue;
+ (BOOL)VhalfScore:(NSInteger)ZBValue;
+ (BOOL)ojiaoqiuScore:(NSInteger)ZBValue;
+ (BOOL)Hlabstate:(NSInteger)ZBValue;
+ (BOOL)vjianBtn:(NSInteger)ZBValue;
+ (BOOL)tbaoBtn:(NSInteger)ZBValue;
+ (BOOL)mattentionBtn:(NSInteger)ZBValue;
+ (BOOL)nredHomeLab:(NSInteger)ZBValue;
+ (BOOL)OredAwayLab:(NSInteger)ZBValue;
+ (BOOL)HyellowHomeLab:(NSInteger)ZBValue;
+ (BOOL)gyellowAwayLab:(NSInteger)ZBValue;
+ (BOOL)MlistHomeLab:(NSInteger)ZBValue;
+ (BOOL)qlistAwayLab:(NSInteger)ZBValue;
+ (BOOL)slabRemark:(NSInteger)ZBValue;
+ (BOOL)PaddAutoLayoutToCell:(NSInteger)ZBValue;
+ (BOOL)GAttention:(NSInteger)ZBValue;
+ (BOOL)vUpdateattentionwithidhWhetherselected:(NSInteger)ZBValue;
+ (BOOL)stoFenxiye:(NSInteger)ZBValue;
+ (BOOL)NTofenxiwithmatchidMTopageindexXToitemindex:(NSInteger)ZBValue;

@end
