#import <UIKit/UIKit.h>
#import "ZBDCTabBarController.h"
#import "ZBWebDetailViewController.h"
#import <UserNotifications/UserNotifications.h>
#import "ZBAppDelegate.h"
#import <Photos/Photos.h>
#import "UIImage+ScreenPic.h"
#import "PictureModel.h"
#import <Bugly/Bugly.h>
#import "ZBTuijianDetailVC.h"
#import "ZBAppleIAPService.h"
#import "XHPayKit.h"
#import <UMPush/UMessage.h>
#import "ZBAppConfig.h"
#import "ZBTbableConfig.h"
#import "ArchiveFile.h"
#import "ZBStartViewController.h"
#import "ZBLaunchView.h"
#import "ZBAspectManager.h"
#import "ZBAppDelegate+Zbvalue.h"

@interface ZBAppDelegate (ZbvalueZbvalue)
+ (BOOL)resumePuchaseZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)configPageStatisticsZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidfinishlaunchingwithoptionsZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadConfigZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)setUpMessageSoundZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)svPreferrenceConfZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)getScreenShotZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)userDidScreenShortZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)initRootViewCotrollerZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)initLocalNotificationZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)isFirstLaunchedZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)updataLocalSaveDataZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)getUrlSerPathZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)setupUPushWithWithoptionsZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)setupUMZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidreceiveremotenotificationFetchcompletionhandlerZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)userNotificationCenterWillpresentnotificationWithcompletionhandlerZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)userNotificationCenterDidreceivenotificationresponseWithcompletionhandlerZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidreceiveremotenotificationZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidregisterforremotenotificationswithdevicetokenZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)setUpBuglyZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)setUpFPSZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)setUMShareZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationHandleopenurlZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationOpenurlSourceapplicationAnnotationZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationOpenurlOptionsZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationWillResignActiveZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidEnterBackgroundZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationWillEnterForegroundZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidBecomeActiveZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationWillTerminateZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)GetServerUrlZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadLaunchImageViewZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadFirstDataZbvalueZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadrefreshtokenZbvalueZbvalue:(NSInteger)ZBValue;

@end
