#import <UIKit/UIKit.h>
#import "ZBDCTabBarController.h"
#import "ZBWebDetailViewController.h"
#import <UserNotifications/UserNotifications.h>
#import "ZBAppDelegate.h"
#import <Photos/Photos.h>
#import "UIImage+ScreenPic.h"
#import "PictureModel.h"
#import <Bugly/Bugly.h>
#import "ZBTuijianDetailVC.h"
#import "ZBAppleIAPService.h"
#import "XHPayKit.h"
#import <UMPush/UMessage.h>
#import "ZBAppConfig.h"
#import "ZBTbableConfig.h"
#import "ArchiveFile.h"
#import "ZBStartViewController.h"
#import "ZBLaunchView.h"
#import "ZBAspectManager.h"

@interface ZBAppDelegate (Zbvalue)
+ (BOOL)resumePuchaseZbvalue:(NSInteger)ZBValue;
+ (BOOL)configPageStatisticsZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidfinishlaunchingwithoptionsZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadConfigZbvalue:(NSInteger)ZBValue;
+ (BOOL)setUpMessageSoundZbvalue:(NSInteger)ZBValue;
+ (BOOL)svPreferrenceConfZbvalue:(NSInteger)ZBValue;
+ (BOOL)getScreenShotZbvalue:(NSInteger)ZBValue;
+ (BOOL)userDidScreenShortZbvalue:(NSInteger)ZBValue;
+ (BOOL)initRootViewCotrollerZbvalue:(NSInteger)ZBValue;
+ (BOOL)initLocalNotificationZbvalue:(NSInteger)ZBValue;
+ (BOOL)isFirstLaunchedZbvalue:(NSInteger)ZBValue;
+ (BOOL)updataLocalSaveDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)getUrlSerPathZbvalue:(NSInteger)ZBValue;
+ (BOOL)setupUPushWithWithoptionsZbvalue:(NSInteger)ZBValue;
+ (BOOL)setupUMZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidreceiveremotenotificationFetchcompletionhandlerZbvalue:(NSInteger)ZBValue;
+ (BOOL)userNotificationCenterWillpresentnotificationWithcompletionhandlerZbvalue:(NSInteger)ZBValue;
+ (BOOL)userNotificationCenterDidreceivenotificationresponseWithcompletionhandlerZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidreceiveremotenotificationZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidregisterforremotenotificationswithdevicetokenZbvalue:(NSInteger)ZBValue;
+ (BOOL)setUpBuglyZbvalue:(NSInteger)ZBValue;
+ (BOOL)setUpFPSZbvalue:(NSInteger)ZBValue;
+ (BOOL)setUMShareZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationHandleopenurlZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationOpenurlSourceapplicationAnnotationZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationOpenurlOptionsZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationWillResignActiveZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidEnterBackgroundZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationWillEnterForegroundZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationDidBecomeActiveZbvalue:(NSInteger)ZBValue;
+ (BOOL)applicationWillTerminateZbvalue:(NSInteger)ZBValue;
+ (BOOL)GetServerUrlZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadLaunchImageViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadFirstDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadrefreshtokenZbvalue:(NSInteger)ZBValue;

@end
