#import "ZBViewPagerController.h"
#import "ZBBasicViewController.h"
#import "ZBBifenViewController.h"
#import "ZBLiveScoreModel.h"
#import "ZBLivingModel.h"
#import "ZBQiciModel.h"
#import "ZBBifenSetingViewController.h"
#import "ZBSearchMatchVC.h"
#import "ZBSaishiSelecterdVC.h"
#import "ZBBIfenSelectedSaishiModel.h"
#import "ZBJishiViewController.h"
#import "ZBSaiguoViewController.h"
#import "ZBSaichengViewController.h"
#import "ZBGuanzhuViewController.h"
#import "ZBSelecterMatchView.h"
#import "ZBSelectedEventView.h"
#import "ZBHSTabBarContentView.h"
#import "ArchiveFile.h"

@interface ZBBifenViewController (Zbvalue)
+ (BOOL)preferredStatusBarStyleZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillAppearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)titleArrZbvalue:(NSInteger)ZBValue;
+ (BOOL)navTitleViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)setNavViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnSearchZbvalue:(NSInteger)ZBValue;
+ (BOOL)colorForTabBarItemTextInTabBarContentViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)highlightColorForTabBarItemInTabBarContentViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)highlightViewForTabBarItemInTabBarContentViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)tabBarContentViewDidselectitematindexZbvalue:(NSInteger)ZBValue;
+ (BOOL)numberOfItemsInTabBarContentViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)tabBarContentViewTitleforitematindexZbvalue:(NSInteger)ZBValue;
+ (BOOL)tabBarContentViewContentviewatindexZbvalue:(NSInteger)ZBValue;
+ (BOOL)navViewTouchAnIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)selectedMatchZbvalue:(NSInteger)ZBValue;
+ (BOOL)matchViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)touchTapViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)ZBSelecterMatchViewSelectedatindexZbvalue:(NSInteger)ZBValue;
+ (BOOL)showOrhideMatchViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidLoadZbvalue:(NSInteger)ZBValue;
+ (BOOL)updateWhetherShowSortZbvalue:(NSInteger)ZBValue;
+ (BOOL)attentionClickZbvalue:(NSInteger)ZBValue;
+ (BOOL)settableViewContentOffsetZeroZbvalue:(NSInteger)ZBValue;
+ (BOOL)TitleViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)didSelectedAtIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)numberOfTabsForViewPagerZbvalue:(NSInteger)ZBValue;
+ (BOOL)jishiVCZbvalue:(NSInteger)ZBValue;
+ (BOOL)saiguoVCZbvalue:(NSInteger)ZBValue;
+ (BOOL)saichengVCZbvalue:(NSInteger)ZBValue;
+ (BOOL)guanzhuVCZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewPagerContentviewcontrollerfortabatindexZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewPagerDidchangetabtoindexZbvalue:(NSInteger)ZBValue;
+ (BOOL)setCurrentIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollEnabledZbvalue:(NSInteger)ZBValue;
+ (BOOL)updateByselectedsaishiZbvalue:(NSInteger)ZBValue;
+ (BOOL)getAttentionNumZbvalue:(NSInteger)ZBValue;
+ (BOOL)stayZbvalue:(NSInteger)ZBValue;
+ (BOOL)didReceiveMemoryWarningZbvalue:(NSInteger)ZBValue;

@end
