#import "ZBBasicViewController.h"
#import "ZBViewPagerController.h"
#import "ZBLiveScoreModel.h"
#import "ZBDCScrollVIew.h"
#import "ZBFenxiHeaderView.h"
#import "PictureModel.h"
#import "ZBFenxiPageVC.h"
#import "ZBBifenDTTable.h"
#import "ZBNewQingbaoTableView.h"
#import "ZBInfoListModel.h"
#import "ZBTuijianDatingTableView.h"
#import "ZBTitleIndexView.h"
#import "ZBLivingModel.h"
#import "ZBTimeModel.h"
#import "ZBNewTuijianHtml.h"
#import "ZBZhiboTableView.h"
#import "ZBJiBenWebView.h"
#import "ZBRelRecNewVC.h"
#import "ZBToAnalystsVC.h"
#import "ZBFenXiHeaderBottomView.h"
#import "SRWebSocket.h"
#import "ZBRecommendedWebView.h"
#import "ArchiveFile.h"
#import "ZBToolWebViewController.h"
#import "ZBAnalysisWebview.h"
#import "ZBShowActivityView.h"
#import "ZBRecommendedWKWeb.h"

@interface ZBFenxiPageVC (Zbvalue)
+ (BOOL)preferredStatusBarStyleZbvalue:(NSInteger)ZBValue;
+ (BOOL)deallocZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidLoadZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillAppearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)timerRunZbvalue:(NSInteger)ZBValue;
+ (BOOL)timerChangeZbvalue:(NSInteger)ZBValue;
+ (BOOL)startTimeZbvalue:(NSInteger)ZBValue;
+ (BOOL)setNavViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)navViewTouchAnIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)changeTableViewFrameZbvalue:(NSInteger)ZBValue;
+ (BOOL)updateHeaderDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)numberOfSectionsInTableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewNumberofrowsinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforheaderinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewViewforheaderinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewCellforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)didReceiveMemoryWarningZbvalue:(NSInteger)ZBValue;
+ (BOOL)headerViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)hederBottomViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)backClickZbvalue:(NSInteger)ZBValue;
+ (BOOL)rightBtnClickZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollMainViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnFabuCilickZbvalue:(NSInteger)ZBValue;
+ (BOOL)toapplyAnalasisZbvalue:(NSInteger)ZBValue;
+ (BOOL)NewQBTableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)headerRefreshNewQBZbvalue:(NSInteger)ZBValue;
+ (BOOL)tuiJianTableZbvalue:(NSInteger)ZBValue;
+ (BOOL)recommendWebZbvalue:(NSInteger)ZBValue;
+ (BOOL)webViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)analysisWebZbvalue:(NSInteger)ZBValue;
+ (BOOL)webViewZhiShuZbvalue:(NSInteger)ZBValue;
+ (BOOL)webZhiBoZbvalue:(NSInteger)ZBValue;
+ (BOOL)titleViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)didSelectedAtIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidEndDeceleratingZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)setsubvewCanscrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)setCurrentIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)lodaDataTiDianZbvalue:(NSInteger)ZBValue;
+ (BOOL)lodaDataAnalysisQBZbvalue:(NSInteger)ZBValue;
+ (BOOL)uploadImageWithImageArrCompletionZbvalue:(NSInteger)ZBValue;
+ (BOOL)handlePanZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadLiveDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)liveQuziActionZbvalue:(NSInteger)ZBValue;
+ (BOOL)liveQuizImageViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)animationActivityViewZbvalue:(NSInteger)ZBValue;

@end
