#import "ZBBasicViewController.h"
#import "ArchiveFile.h"
#import "ZBLiveQuizViewController.h"
#import "ZBWebModel.h"
#import "ZBFirstViewController.h"
#import "ZBFocusModel.h"
#import "ZBNewslistModel.h"
#import "ZBFirstPInfoListModel.h"
#import "ZBUserlistModel.h"
#import "ZBRollInfoModel.h"
#import "ZBTuijiandatingModel.h"
#import "ZBWebDetailViewController.h"
#import "ZBLoadHtmlStringVC.h"
#import "ZBTuijianDatingCell.h"
#import "ZBNewRecommandVC.h"
#import "ZBfirstHotInfoCycleView.h"
#import "ZBFirstPUserlistView.h"
#import "ZBTuijianDetailVC.h"
#import "ZBJiXianVC.h"
#import "ZBBettingVC.h"
#import "ZBPanwangZhishuVC.h"
#import "ZBJiaoYiViewController.h"
#import "ZBBaolengZhishuVC.h"
#import "ZBTongpeiTongjiVC.h"
#import "ZBPeilvYichangVC.h"
#import "ZBYapanZhoushouVC.h"
#import "ZBVierticalScrollView.h"
#import "ZBFenxiPageVC.h"
#import "ZBTuijianDTViewController.h"
#import "ZBLaunchView.h"
#import "ZBGuideView.h"
#import "ZBTodayHotSpotsCell.h"
#import "ZBRedDanCycleView.h"
#import "ZBTuijianDatingCell.h"
#import "ZBTuijiandatingModel.h"
#import "ZBRedDanModel.h"
#import "ZBMostModel.h"
#import "ZBLivingModel.h"
#import "ZBDataModelView.h"
#import "ZBTodayHotSpotsTwoCell.h"
#import "ZBModelPredictionViewController.h"
#import "ZBToolKitViewController.h"
#import "ZBLiveViewController.h"
#import "ZBToolWebViewController.h"

@interface ZBFirstViewController (Zbvalue)
+ (BOOL)preferredStatusBarStyleZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillAppearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidAppearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)changeTimerZbvalue:(NSInteger)ZBValue;
+ (BOOL)timerChangeZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidLoadZbvalue:(NSInteger)ZBValue;
+ (BOOL)setTableViewContentOffsetZeroZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)emptyDataSetDidtapviewZbvalue:(NSInteger)ZBValue;
+ (BOOL)imageForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)imageAnimationForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)emptyDataSetShouldAllowScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)setTableHeaderZbvalue:(NSInteger)ZBValue;
+ (BOOL)headerRefreshZbvalue:(NSInteger)ZBValue;
+ (BOOL)numberOfSectionsInTableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewNumberofrowsinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)firstPgZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewCellforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)dicSelectedToFenxiWithModelZbvalue:(NSInteger)ZBValue;
+ (BOOL)selectedUserWithIdZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewViewforheaderinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewViewforfooterinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnUserBtnZbvalue:(NSInteger)ZBValue;
+ (BOOL)toMoreZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforheaderinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforfooterinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewDidselectrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)cycleScrollViewDidselectitematindexZbvalue:(NSInteger)ZBValue;
+ (BOOL)cycleScrollViewDidscrolltoindexZbvalue:(NSInteger)ZBValue;
+ (BOOL)clickTitleButtonZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewInfoZbvalue:(NSInteger)ZBValue;
+ (BOOL)didSelectedDataModelViewIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)toFenxiWithMatchIdTopageindexToitemindexZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewWillBeginDraggingZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateZbvalue:(NSInteger)ZBValue;
+ (BOOL)getParentViewOfTitleAndMessageFromViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)didReceiveMemoryWarningZbvalue:(NSInteger)ZBValue;
+ (BOOL)handlePanZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadLiveDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)liveQuziActionZbvalue:(NSInteger)ZBValue;
+ (BOOL)liveQuizImageViewZbvalue:(NSInteger)ZBValue;

@end
