#import "ZBBasicViewController.h"
#import "ZBJishiViewController.h"
#import "ZBSaiguoViewController.h"
#import "ZBSaichengViewController.h"
#import "ZBGuanzhuViewController.h"
#import "ZBHSJFoldHeaderView.h"
#import "ZBWebView.h"
#import "ZBSaiTableViewCell.h"
#import "ZBLiveScoreModel.h"
#import "ZBQiciModel.h"
#import "ZBDCJishiBIifenView.h"
#import "ZBDCPlaySound.h"
#import "ZBBIfenSelectedSaishiModel.h"
#import "ZBDCindexBtn.h"
#import "ZBJSbifenModel.h"

@interface ZBJishiViewController (Zbvalue)
+ (BOOL)preferredStatusBarStyleZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillAppearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidLoadZbvalue:(NSInteger)ZBValue;
+ (BOOL)creatArrZbvalue:(NSInteger)ZBValue;
+ (BOOL)titleArrZbvalue:(NSInteger)ZBValue;
+ (BOOL)getNewDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)refreshDataByChangeFlagZbvalue:(NSInteger)ZBValue;
+ (BOOL)didReceiveMemoryWarningZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)setupHeaderViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)headerRefreshDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)numberOfSectionsInTableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforheaderinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewViewforheaderinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewNumberofrowsinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewCellforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)indexBtnZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollToScaleZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidEndDeceleratingZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidEndScrollingAnimationZbvalue:(NSInteger)ZBValue;
+ (BOOL)hideIndexBtnZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewWillBeginDraggingZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewDidselectrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)emptyDataSetDidtapviewZbvalue:(NSInteger)ZBValue;
+ (BOOL)observeValueForKeyPathOfobjectChangeContextZbvalue:(NSInteger)ZBValue;
+ (BOOL)imageAnimationForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)imageForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)titleForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)emptyDataSetShouldAllowScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadDataQiciJishiViewControllerZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadDataJishiViewControllerWithQiciZbvalue:(NSInteger)ZBValue;
+ (BOOL)seperateAlldateArrayByArrayZbvalue:(NSInteger)ZBValue;
+ (BOOL)foldHeaderInSectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)changeTimerZbvalue:(NSInteger)ZBValue;
+ (BOOL)gcdTimerZbvalue:(NSInteger)ZBValue;
+ (BOOL)timerRunZbvalue:(NSInteger)ZBValue;
+ (BOOL)hudZbvalue:(NSInteger)ZBValue;
+ (BOOL)jsbfViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)changeLivingScoreWithDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)jinqiuShowHudWithLivingModelNowmodelZbvalue:(NSInteger)ZBValue;
+ (BOOL)reloadTableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)hongpaiShowHudLivingModelNowmodelZbvalue:(NSInteger)ZBValue;
+ (BOOL)musicShowRedZbvalue:(NSInteger)ZBValue;
+ (BOOL)musicShowJinqiuZbvalue:(NSInteger)ZBValue;
+ (BOOL)getLivetimeZbvalue:(NSInteger)ZBValue;
+ (BOOL)showJinqiuHudZbvalue:(NSInteger)ZBValue;
+ (BOOL)hideJinqiuHudAfterSecondsZbvalue:(NSInteger)ZBValue;
+ (BOOL)staybifenZbvalue:(NSInteger)ZBValue;
+ (BOOL)webCloseZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadRedBombActivityZbvalue:(NSInteger)ZBValue;
+ (BOOL)addActivityWithZbvalue:(NSInteger)ZBValue;
+ (BOOL)redBombActivityZbvalue:(NSInteger)ZBValue;
+ (BOOL)closeActivityZbvalue:(NSInteger)ZBValue;
+ (BOOL)activityImageViewZbvalue:(NSInteger)ZBValue;

@end
