#import "ZBBasicViewController.h"
#import "ZBDan_StringMatchsModel.h"
#import "ImageTextAttachment.h"
#import "NSAttributedString+html.h"
#import "PictureModel.h"
#import "NSString+Regular.h"
#import "NSAttributedString+RichText.h"
#import "ZBSelectedViewOfFabuTuijian.h"
#import "ZBZhumaViewOfFabuTuijian.h"
#import "ZBRelRecNewVC.h"
#import "ZBTitleIndexView.h"
#import "ZBFaBuSucceedVCViewController.h"
#import "ZBToAnalystsVC.h"

@interface ZBRelRecNewVC (Zbvalue)
+ (BOOL)viewWillAppearZbvalue:(NSInteger)ZBValue;
+ (BOOL)preferredStatusBarStyleZbvalue:(NSInteger)ZBValue;
+ (BOOL)setNavViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)navViewTouchAnIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidLoadZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)setupModelZbvalue:(NSInteger)ZBValue;
+ (BOOL)fabuTuijianZbvalue:(NSInteger)ZBValue;
+ (BOOL)leftBarButtonItemZbvalue:(NSInteger)ZBValue;
+ (BOOL)ScrollViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)testViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDetialTitleZbvalue:(NSInteger)ZBValue;
+ (BOOL)rqBaseViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)labRQZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnZhuZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnKeZbvalue:(NSInteger)ZBValue;
+ (BOOL)dxBaseViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)labDXQZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnBigZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnLittleZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDetialZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnOneZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnTwoZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnThreeZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnColickOddsZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewZhumaZbvalue:(NSInteger)ZBValue;
+ (BOOL)didselectedZhumaAtIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)didselectedPriceViewWithModelZbvalue:(NSInteger)ZBValue;
+ (BOOL)ViewTextTitleZbvalue:(NSInteger)ZBValue;
+ (BOOL)switchActionZbvalue:(NSInteger)ZBValue;
+ (BOOL)toapplyAnalasisZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewPlaceholderZbvalue:(NSInteger)ZBValue;
+ (BOOL)buttomViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)tapButtomViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnPhotoZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewDidChangeZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewShouldBeginEditingZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewDidEndEditingZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewShouldchangetextinrangeReplacementtextZbvalue:(NSInteger)ZBValue;
+ (BOOL)stringContainsEmojiZbvalue:(NSInteger)ZBValue;
+ (BOOL)KeyboardShowZbvalue:(NSInteger)ZBValue;
+ (BOOL)KeyboardHideZbvalue:(NSInteger)ZBValue;
+ (BOOL)AddPicZbvalue:(NSInteger)ZBValue;
+ (BOOL)imagePickerControllerDidfinishpickingmediawithinfoZbvalue:(NSInteger)ZBValue;
+ (BOOL)imagePickerControllerDidCancelZbvalue:(NSInteger)ZBValue;
+ (BOOL)setImageTextWithrangeAppenreturnZbvalue:(NSInteger)ZBValue;
+ (BOOL)appenReturnZbvalue:(NSInteger)ZBValue;
+ (BOOL)setInitLocationZbvalue:(NSInteger)ZBValue;
+ (BOOL)uploadImageZbvalue:(NSInteger)ZBValue;
+ (BOOL)replacetagWithImageArrayZbvalue:(NSInteger)ZBValue;
+ (BOOL)getPPPZbvalue:(NSInteger)ZBValue;
+ (BOOL)filterHTMLZbvalue:(NSInteger)ZBValue;
+ (BOOL)fabuTuijianWithHtmlWithcontentZbvalue:(NSInteger)ZBValue;
+ (BOOL)updateModelZbvalue:(NSInteger)ZBValue;
+ (BOOL)didReceiveMemoryWarningZbvalue:(NSInteger)ZBValue;

@end
