#import "ZBBasicViewController.h"
#import "ZBSaiTableViewCell.h"
#import "ZBLiveScoreModel.h"
#import "ZBQiciModel.h"
#import "ZBBIfenSelectedSaishiModel.h"
#import "ZBJSbifenModel.h"
#import "ZBSaiguoViewController.h"
#import "ZBSelectedDataView.h"
#import "ZBSelectedDateTitleView.h"
#import "ZBSelectedSaiGuoTitleView.h"
#import "ZBDCindexBtn.h"
#import "ZBSelectedDTitleView.h"
#import "ZBHSInfiniteScrollView.h"
#import "ZBHSDashLineView.h"

@interface ZBSaiguoViewController (Zbvalue)
+ (BOOL)initZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillAppearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidLoadZbvalue:(NSInteger)ZBValue;
+ (BOOL)changeShowTypeZbvalue:(NSInteger)ZBValue;
+ (BOOL)ContenViewTapFreshZbvalue:(NSInteger)ZBValue;
+ (BOOL)dataLineViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)saiGuoTitleViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)selectedSaiGuoViewIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)dataTitleViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)selectedDateViewIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)dataViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)ZBSelecterMatchViewSelectedatindexWithselectednameZbvalue:(NSInteger)ZBValue;
+ (BOOL)touchTapViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)showOrhideDateViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)didReceiveMemoryWarningZbvalue:(NSInteger)ZBValue;
+ (BOOL)refreshDataByChangeFlagZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)emptyDataSetDidtapviewZbvalue:(NSInteger)ZBValue;
+ (BOOL)imageForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)titleForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)emptyDataSetShouldAllowScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)indexBtnZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollToScaleZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidEndDeceleratingZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidEndScrollingAnimationZbvalue:(NSInteger)ZBValue;
+ (BOOL)hideIndexBtnZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewWillBeginDraggingZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewDidselectrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)setupHeaderViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)headerRefreshDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)numberOfSectionsInTableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewNumberofrowsinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewCellforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadDataQiciJishiViewControllerZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadDataJishiViewControllerWithQiciZbvalue:(NSInteger)ZBValue;
+ (BOOL)clearSelectedSavedZbvalue:(NSInteger)ZBValue;

@end
