#import <UIKit/UIKit.h>
#import "ZBWebModel.h"
#import "ZBSelectPayMentView.h"
#import "ZBBasicViewController.h"
#import <WebKit/WebKit.h>
#import "ZBToolWebViewController.h"
#import "WebViewJavascriptBridge.h"
#import "ZBUserModel.h"
#import "ZBTokenModel.h"
#import "ZBAppleIAPService.h"
#import <UShareUI/UShareUI.h>
#import "ZBCouponListViewController.h"
#import "ZBLiveQuizWithDrawalViewController.h"
#import "XHPayKit.h"
#import "ArchiveFile.h"
#import "ZBAppManger.h"
#import "ZBNavImageView.h"
#import "ZBWebView.h"
#import "ZBLiveQuizViewController.h"
#import "ZBLotteryWebViewController.h"
#import "ZBCommentsView.h"
#import "ZBCommentsViewController.h"
#import "ZBInputViewController.h"

@interface ZBToolWebViewController (Zbvalue)
+ (BOOL)viewDidLoadZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillAppearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)didReceiveMemoryWarningZbvalue:(NSInteger)ZBValue;
+ (BOOL)deallocZbvalue:(NSInteger)ZBValue;
+ (BOOL)refreshResultZbvalue:(NSInteger)ZBValue;
+ (BOOL)refreshDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)observeValueForKeyPathOfobjectChangeContextZbvalue:(NSInteger)ZBValue;
+ (BOOL)webViewDecidepolicyfornavigationactionDecisionhandlerZbvalue:(NSInteger)ZBValue;
+ (BOOL)webViewDidstartprovisionalnavigationZbvalue:(NSInteger)ZBValue;
+ (BOOL)webViewDidfinishnavigationZbvalue:(NSInteger)ZBValue;
+ (BOOL)webViewDidfailprovisionalnavigationWitherrorZbvalue:(NSInteger)ZBValue;
+ (BOOL)webViewWebContentProcessDidTerminateZbvalue:(NSInteger)ZBValue;
+ (BOOL)commentViewDidSelectCommnetListZbvalue:(NSInteger)ZBValue;
+ (BOOL)commentViewDidSelectReplyZbvalue:(NSInteger)ZBValue;
+ (BOOL)commentViewDidSelectShareZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadBradgeHandlerZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)configWebHeightZbvalue:(NSInteger)ZBValue;
+ (BOOL)configUIZbvalue:(NSInteger)ZBValue;
+ (BOOL)webCloseZbvalue:(NSInteger)ZBValue;
+ (BOOL)closeWinZbvalue:(NSInteger)ZBValue;
+ (BOOL)webBackZbvalue:(NSInteger)ZBValue;
+ (BOOL)webShareZbvalue:(NSInteger)ZBValue;
+ (BOOL)backZbvalue:(NSInteger)ZBValue;
+ (BOOL)openH5Zbvalue:(NSInteger)ZBValue;
+ (BOOL)openNativeZbvalue:(NSInteger)ZBValue;
+ (BOOL)payZbvalue:(NSInteger)ZBValue;
+ (BOOL)navZbvalue:(NSInteger)ZBValue;
+ (BOOL)pagetoolbarZbvalue:(NSInteger)ZBValue;
+ (BOOL)getJSONMessageZbvalue:(NSInteger)ZBValue;
+ (BOOL)pushToMatchDetailZbvalue:(NSInteger)ZBValue;
+ (BOOL)toFenxiWithMatchIdTopageindexToitemindexZbvalue:(NSInteger)ZBValue;
+ (BOOL)createNullToastViewImagenameZbvalue:(NSInteger)ZBValue;
+ (BOOL)dissMissToastViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)reloadActionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableBarActionZbvalue:(NSInteger)ZBValue;
+ (BOOL)buyActionZbvalue:(NSInteger)ZBValue;
+ (BOOL)currentPageZbvalue:(NSInteger)ZBValue;
+ (BOOL)payActionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tencentBuyWithDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)alibuyWithDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)appleBuyWithDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)couponBuyWithDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)containsClassNameZbvalue:(NSInteger)ZBValue;
+ (BOOL)indexWithClassNameZbvalue:(NSInteger)ZBValue;
+ (BOOL)wkWebZbvalue:(NSInteger)ZBValue;
+ (BOOL)commentsViewZbvalue:(NSInteger)ZBValue;

@end
