#import <UIKit/UIKit.h>
#import "ZBTuijiandatingModel.h"
#import "ZBTuijianDetailHeaderView.h"
#import "ZBUserViewOfTuijianCell.h"
#import "ZBDC_JZAPhotoVC.h"
#import "ZBLiveScoreModel.h"
#import "ZBFenxiPageVC.h"

@interface ZBTuijianDetailHeaderView (Zbvalue)
+ (BOOL)awakeFromNibZbvalue:(NSInteger)ZBValue;
+ (BOOL)setSelectedAnimatedZbvalue:(NSInteger)ZBValue;
+ (BOOL)setModelZbvalue:(NSInteger)ZBValue;
+ (BOOL)basicViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)headerUserZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewLineAuthorBottomZbvalue:(NSInteger)ZBValue;
+ (BOOL)labSaishiZbvalue:(NSInteger)ZBValue;
+ (BOOL)labbeginTimeZbvalue:(NSInteger)ZBValue;
+ (BOOL)labQiciZbvalue:(NSInteger)ZBValue;
+ (BOOL)imageViewHomeZbvalue:(NSInteger)ZBValue;
+ (BOOL)labTeamHomeZbvalue:(NSInteger)ZBValue;
+ (BOOL)labVSZbvalue:(NSInteger)ZBValue;
+ (BOOL)imageViewGuestZbvalue:(NSInteger)ZBValue;
+ (BOOL)labTeamGuestZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnToBiFenZbvalue:(NSInteger)ZBValue;
+ (BOOL)allBtnZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnToBiFenClickZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewLineTeamBottomZbvalue:(NSInteger)ZBValue;
+ (BOOL)labPankouZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnWinZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnPingZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnLoseZbvalue:(NSInteger)ZBValue;
+ (BOOL)labMultipleTitleZbvalue:(NSInteger)ZBValue;
+ (BOOL)imageMultipleZbvalue:(NSInteger)ZBValue;
+ (BOOL)labMultipleZbvalue:(NSInteger)ZBValue;
+ (BOOL)labCompanyZbvalue:(NSInteger)ZBValue;
+ (BOOL)labReasonZbvalue:(NSInteger)ZBValue;
+ (BOOL)redViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)redView1Zbvalue:(NSInteger)ZBValue;
+ (BOOL)redView2Zbvalue:(NSInteger)ZBValue;
+ (BOOL)labContentZbvalue:(NSInteger)ZBValue;
+ (BOOL)labcontentPartZbvalue:(NSInteger)ZBValue;
+ (BOOL)labcontentPartDetailZbvalue:(NSInteger)ZBValue;
+ (BOOL)labhidecontentPartDetailZbvalue:(NSInteger)ZBValue;
+ (BOOL)imgcontentPartZbvalue:(NSInteger)ZBValue;
+ (BOOL)imghidecontentZbvalue:(NSInteger)ZBValue;
+ (BOOL)labMoneyZbvalue:(NSInteger)ZBValue;
+ (BOOL)webViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)webViewShouldstartloadwithrequestNavigationtypeZbvalue:(NSInteger)ZBValue;
+ (BOOL)webViewDidFinishLoadZbvalue:(NSInteger)ZBValue;
+ (BOOL)labCreatTimeZbvalue:(NSInteger)ZBValue;
+ (BOOL)labConmmentNumZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnCommentZbvalue:(NSInteger)ZBValue;
+ (BOOL)labNoZanNumZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnNoZanZbvalue:(NSInteger)ZBValue;
+ (BOOL)labZanNumZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnZanZbvalue:(NSInteger)ZBValue;
+ (BOOL)imageViewWinZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewLineBasicViewBottomZbvalue:(NSInteger)ZBValue;
+ (BOOL)addAutoLayoutToCellZbvalue:(NSInteger)ZBValue;
+ (BOOL)addLikedHatedZbvalue:(NSInteger)ZBValue;
+ (BOOL)reportZbvalue:(NSInteger)ZBValue;
+ (BOOL)alertViewClickedbuttonatindexZbvalue:(NSInteger)ZBValue;
+ (BOOL)sendReportInfomationWithcategoryZbvalue:(NSInteger)ZBValue;

@end
