#import "ZBBasicViewController.h"
#import "ZBTuijiandatingModel.h"
#import "ZBTuijianDetailTableView.h"
#import "ZBTuijianDetailVC.h"
#import "ZBCommentModel.h"
#import "ZBBuyRecordsVC.h"
#import "ZBBuyerModel.h"
#import "ZBpayUserModel.h"
#import "ZBTuijianDetailHeaderView.h"
#import "ZBTuijianDTViewController.h"
#import "ZBAppleIAPService.h"
#import "ZBSelectPayMentView.h"
#import "ArchiveFile.h"
#import "XHPayKit.h"
#import "ZBToolWebViewController.h"
#import "ZBWebModel.h"
#import "NSString+XHPayKit.h"

@interface ZBTuijianDetailVC (Zbvalue)
+ (BOOL)viewWillAppearZbvalue:(NSInteger)ZBValue;
+ (BOOL)preferredStatusBarStyleZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidLoadZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewdatanewZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)addCommentZbvalue:(NSInteger)ZBValue;
+ (BOOL)setNavViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)navViewTouchAnIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)addAutoLayoutZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)appIdStrZbvalue:(NSInteger)ZBValue;
+ (BOOL)bottomViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)payViewpaylZbvalue:(NSInteger)ZBValue;
+ (BOOL)addCommentZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)sendBtnZbvalue:(NSInteger)ZBValue;
+ (BOOL)cancelBtnZbvalue:(NSInteger)ZBValue;
+ (BOOL)cancelCommentZbvalue:(NSInteger)ZBValue;
+ (BOOL)sendCommentZbvalue:(NSInteger)ZBValue;
+ (BOOL)labCommentZbvalue:(NSInteger)ZBValue;
+ (BOOL)labCommentNumZbvalue:(NSInteger)ZBValue;
+ (BOOL)labComment1Zbvalue:(NSInteger)ZBValue;
+ (BOOL)labCommentNum1Zbvalue:(NSInteger)ZBValue;
+ (BOOL)labelQiuBiZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnPayZbvalue:(NSInteger)ZBValue;
+ (BOOL)payBtnClickZbvalue:(NSInteger)ZBValue;
+ (BOOL)zhucetongzhiZbvalue:(NSInteger)ZBValue;
+ (BOOL)wxtongzhiZbvalue:(NSInteger)ZBValue;
+ (BOOL)paySuccessZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidLayoutSubviewsZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewShouldchangetextinrangeReplacementtextZbvalue:(NSInteger)ZBValue;
+ (BOOL)stringContainsEmojiZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewShouldBeginEditingZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewDidBeginEditingZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewDidEndEditingZbvalue:(NSInteger)ZBValue;
+ (BOOL)textViewDidChangeZbvalue:(NSInteger)ZBValue;
+ (BOOL)KeyboardShowZbvalue:(NSInteger)ZBValue;
+ (BOOL)KeyboardHideZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadDataWhetherFirstZbvalue:(NSInteger)ZBValue;
+ (BOOL)sendCommentWithCommentTagWithdictZbvalue:(NSInteger)ZBValue;
+ (BOOL)addLikedZbvalue:(NSInteger)ZBValue;
+ (BOOL)didReceiveMemoryWarningZbvalue:(NSInteger)ZBValue;
+ (BOOL)buyActionWithOptionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tencentBuyWithDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)alibuyWithDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)appleBuyWithDataZbvalue:(NSInteger)ZBValue;

@end
