#import "ZBViewPagerController.h"
#import "ZBUserViewController.h"
#import "ZBUserOfotherCellTwo.h"
#import "ZBUserTongjiCell.h"
#import "ZBUserTongjiGoodPlayCell.h"
#import "ZBTuijianDatingCell.h"
#import "ZBTuijiandatingModel.h"
#import "ZBUserTuijianVC.h"
#import "ZBUserTongjiAllModel.h"
#import "ZBWebView.h"
#import "ZBTongjiVC.h"
#import "ZBTopContentView.h"

@interface ZBUserViewController (Zbvalue)
+ (BOOL)viewWillAppearZbvalue:(NSInteger)ZBValue;
+ (BOOL)preferredStatusBarStyleZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewDidLoadZbvalue:(NSInteger)ZBValue;
+ (BOOL)viewWillDisappearZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)setupTableViewMJHeaderZbvalue:(NSInteger)ZBValue;
+ (BOOL)emptyDataSetDidtapviewZbvalue:(NSInteger)ZBValue;
+ (BOOL)imageForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)titleForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)emptyDataSetShouldAllowScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewWillBeginDraggingZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidEndDraggingWilldecelerateZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewDidselectrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)numberOfSectionsInTableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforfooterinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewViewforfooterinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforheaderinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewViewforheaderinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)didToTongjiVCZbvalue:(NSInteger)ZBValue;
+ (BOOL)btnTuijianClickZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewNumberofrowsinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewCellforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)getCommentUserInfoZbvalue:(NSInteger)ZBValue;
+ (BOOL)upDownBtnClickZbvalue:(NSInteger)ZBValue;
+ (BOOL)attentionBtnClickZbvalue:(NSInteger)ZBValue;
+ (BOOL)navBtnClickZbvalue:(NSInteger)ZBValue;
+ (BOOL)addAtentionZbvalue:(NSInteger)ZBValue;
+ (BOOL)lodaRecommandDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadTongjiDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)setNavViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)navViewTouchAnIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)didReceiveMemoryWarningZbvalue:(NSInteger)ZBValue;
+ (BOOL)topViewZbvalue:(NSInteger)ZBValue;

@end
