#import "ZBBasicTableView.h"
#import "ZBLiveScoreModel.h"
#import "SRWebSocket.h"
#import "ZBZhiboTableView.h"
#import "ZBLiveEventMedel.h"
#import "ZBliveLineupModel.h"
#import "ZBTechModel.h"
#import "ZBTechtwoModel.h"
#import "ZBJishiFirstCell.h"
#import "ZBJiShiPeiLvCell.h"
#import "ZBPeiLvDetailCell.h"
#import "ZBJiShiPeiLvDetailModel.h"
#import "ZBLiveScoreModel.h"
#import "ZBJiShiPeiLvDetailModel.h"
#import "ZBDoubleBattlecell.h"
#import "ZBPeiLvDetailVC.h"
#import "ZBHSJFoldHeaderView.h"
#import "ZBJSPLDownCell.h"
#import "ZBJSPLDownMode.h"
#import "ZBBisaiTongjiCell.h"
#import "ZBBisaiTongjiCellTwo.h"
#import "ZBBisaiTJHeaderView.h"
#import "ZBBattleModel.h"
#import "ZBJSPLDownMode.h"
#import "ZBJSPLDownTwoModel.h"
#import "ZBTongJiModel.h"

@interface ZBZhiboTableView (Zbvalue)
+ (BOOL)initWithFrameStyleZbvalue:(NSInteger)ZBValue;
+ (BOOL)InfoNotificationActionZbvalue:(NSInteger)ZBValue;
+ (BOOL)setModelZbvalue:(NSInteger)ZBValue;
+ (BOOL)titleArrZbvalue:(NSInteger)ZBValue;
+ (BOOL)doubleTitleArrZbvalue:(NSInteger)ZBValue;
+ (BOOL)creatArrZbvalue:(NSInteger)ZBValue;
+ (BOOL)addSegMentZbvalue:(NSInteger)ZBValue;
+ (BOOL)changIndexZbvalue:(NSInteger)ZBValue;
+ (BOOL)setupTableViewMJHeaderZbvalue:(NSInteger)ZBValue;
+ (BOOL)titleForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)imageForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)emptyDataSetShouldAllowScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)verticalOffsetForEmptyDataSetZbvalue:(NSInteger)ZBValue;
+ (BOOL)numberOfSectionsInTableViewZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewTitleforheaderinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewViewforheaderinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforheaderinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewViewforfooterinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforfooterinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewNumberofrowsinsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewHeightforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewCellforrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewDidselectrowatindexpathZbvalue:(NSInteger)ZBValue;
+ (BOOL)tableViewWilldisplayheaderviewForsectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)scrollViewDidScrollZbvalue:(NSInteger)ZBValue;
+ (BOOL)foldHeaderInSectionZbvalue:(NSInteger)ZBValue;
+ (BOOL)sepreLetGoalArrZbvalue:(NSInteger)ZBValue;
+ (BOOL)sepreOUOddArrZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadJiShiPLDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadDoubleBatDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)loadDataZhiBoZbvalue:(NSInteger)ZBValue;
+ (BOOL)ReconnectZbvalue:(NSInteger)ZBValue;
+ (BOOL)webSocketDidOpenZbvalue:(NSInteger)ZBValue;
+ (BOOL)webSocketDidfailwitherrorZbvalue:(NSInteger)ZBValue;
+ (BOOL)webSocketDidreceivemessageZbvalue:(NSInteger)ZBValue;
+ (BOOL)timerChangeDataZbvalue:(NSInteger)ZBValue;
+ (BOOL)webSocketDidclosewithcodeReasonWascleanZbvalue:(NSInteger)ZBValue;
+ (BOOL)webSocketDidreceivepongZbvalue:(NSInteger)ZBValue;
+ (BOOL)dictionaryWithJsonStringZbvalue:(NSInteger)ZBValue;

@end
